name: Run Automation

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout files
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: workspace/
          tags: ghcr.io/pmh-only/selfgrowing:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          